kind = "web"
previewPath = "/"
title = "PUNTOS | ZAPIA"
version = "1.0.0"
id = "artifacts/puntos"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22773

[services.development]
run = "pnpm --filter @workspace/puntos run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/puntos", "run", "build" ]
publicDir = "artifacts/puntos/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22773"
BASE_PATH = "/"
